plotData <- read.csv("./data/DataHousehold.csv")
temp<-transform(plotData, X=strptime(paste(as.character(plotData$Date),as.character(plotData$Time)), "%d/%m/%Y %H:%M:%S"))
png(file="plot3.png")
plot(temp$X,temp$Sub_metering_1, type="l", xlab=" ", ylab="Energy sub metering")
points (temp$X,temp$Sub_metering_2, type="l", col="red")
points (temp$X,temp$Sub_metering_3, type="l", col="blue")
legend("topright", lty=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
